// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Xrv.LoadModel
{
    public sealed class LoadModelResourceIDs
    {
        public sealed class Materials
        {
            public sealed class Icons
            {
                /// <summary> Asset Path (XRV/Materials/Icons/addModel.wemt) </summary>
                public static readonly Guid addModel = new Guid("84c511cc-7b14-49d2-b4dd-2978038e3a7d");
            }
        }

        public sealed class Models
        {
            /// <summary> Asset Path (XRV/Models/PiggyBot.glb.wemd) </summary>
            public static readonly Guid PiggyBot_glb = new Guid("463dcda2-81af-4e20-9405-d4810990715b");
        }
    }
}
