// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Xrv.LoadModel
{
    public sealed class LoadModelResourceIDs
    {
        public sealed class Materials
        {
            public sealed class Icons
            {
                /// <summary> Asset Path (XRV/Materials/Icons/addModel.wemt) </summary>
                public static readonly Guid addModel = new Guid("84c511cc-7b14-49d2-b4dd-2978038e3a7d");

                /// <summary> Asset Path (XRV/Materials/Icons/delete.wemt) </summary>
                public static readonly Guid delete = new Guid("a7b355f9-51d9-481d-8fde-aa91530be911");

                /// <summary> Asset Path (XRV/Materials/Icons/hamburger.wemt) </summary>
                public static readonly Guid hamburger = new Guid("5b4d2e67-82f7-43da-8a67-0f0b6026cc86");

                /// <summary> Asset Path (XRV/Materials/Icons/locked.wemt) </summary>
                public static readonly Guid locked = new Guid("b424ee14-b54d-4d68-b4b4-cd787859a1cf");

                /// <summary> Asset Path (XRV/Materials/Icons/reset.wemt) </summary>
                public static readonly Guid reset = new Guid("6bf20fcd-0b01-41cc-8e50-9dca6978486c");
            }
        }

        public sealed class Models
        {
            /// <summary> Asset Path (XRV/Models/PiggyBot.glb.wemd) </summary>
            public static readonly Guid PiggyBot_glb = new Guid("463dcda2-81af-4e20-9405-d4810990715b");
        }

        public sealed class Prefabs
        {
            /// <summary> Asset Path (XRV/Prefabs/Manipulator.weprefab.weprf) </summary>
            public static readonly Guid Manipulator_weprefab = new Guid("a632ac02-975c-4940-919e-aa117f62f32c");
        }

        public sealed class MRTK
        {
            public sealed class Materials
            {
                public sealed class BoundingBox
                {

                    /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxHandleBlue.wemt) </summary>
                    public static readonly Guid BoundingBoxHandleBlue = new Guid("9adff77b-f6b6-4683-bf28-243fafea5436");

                    /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxHandleBlueGrabbed.wemt) </summary>
                    public static readonly Guid BoundingBoxHandleBlueGrabbed = new Guid("7c6dfc11-0f01-4d22-bfc9-bc5ca4fae227");

                    /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxVisual.wemt) </summary>
                    public static readonly Guid BoundingBoxVisual = new Guid("76254053-dba8-4ecd-8ffd-2989ae519c06");

                    /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxVisualGrabbed.wemt) </summary>
                    public static readonly Guid BoundingBoxVisualGrabbed = new Guid("0852af68-ed44-4dd5-bebb-05c15449d498");

                    /// <summary> Asset Path (MRTK/Materials/BoundingBox/BoundingBoxWireframe.wemt) </summary>
                    public static readonly Guid BoundingBoxWireframe = new Guid("d04c6b19-b181-4798-8052-73388883abfe");
                }

                public sealed class Buttons
                {
                    /// <summary> Asset Path (XRV/Materials/Buttons/ButtonPrimary.wemt) </summary>
                    public static readonly Guid ButtonPrimary = new Guid("ce1f6bc9-39ac-4a0a-a913-07963f7342f5");
                }
            }

            public sealed class Prefabs
            {
                /// <summary> Asset Path (MRTK/Prefabs/BoundingBox_FaceScaleHandle.weprefab.weprf) </summary>
                public static readonly Guid BoundingBox_FaceScaleHandle_weprefab = new Guid("caa9ea87-b38e-4677-86fb-87ef1cb99838");

                /// <summary> Asset Path (MRTK/Prefabs/BoundingBox_RotateHandle.weprefab.weprf) </summary>
                public static readonly Guid BoundingBox_RotateHandle_weprefab = new Guid("5e18a808-fd7d-49f9-8187-d9256af252c7");

                /// <summary> Asset Path (MRTK/Prefabs/BoundingBox_ScaleHandle.weprefab.weprf) </summary>
                public static readonly Guid BoundingBox_ScaleHandle_weprefab = new Guid("ae0e37ce-4928-42ef-970e-a4b1e547f4ea");
            }
        }
    }
}
