// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Xrv.LoadModel
{
    public sealed class LoadModelResourceIDs
    {
        public sealed class Materials
        {
            public sealed class Icons
            {
                /// <summary> Asset Path (XRV/Materials/Icons/addModel.wemt) </summary>
                public static readonly Guid addModel = new Guid("84c511cc-7b14-49d2-b4dd-2978038e3a7d");

                /// <summary> Asset Path (XRV/Materials/Icons/delete.wemt) </summary>
                public static readonly Guid delete = new Guid("a7b355f9-51d9-481d-8fde-aa91530be911");

                /// <summary> Asset Path (XRV/Materials/Icons/hamburger.wemt) </summary>
                public static readonly Guid hamburger = new Guid("5b4d2e67-82f7-43da-8a67-0f0b6026cc86");

                /// <summary> Asset Path (XRV/Materials/Icons/locked.wemt) </summary>
                public static readonly Guid locked = new Guid("b424ee14-b54d-4d68-b4b4-cd787859a1cf");

                /// <summary> Asset Path (XRV/Materials/Icons/reset.wemt) </summary>
                public static readonly Guid reset = new Guid("6bf20fcd-0b01-41cc-8e50-9dca6978486c");
            }
        }

        public sealed class Models
        {
            /// <summary> Asset Path (XRV/Models/PiggyBot.glb.wemd) </summary>
            public static readonly Guid PiggyBot_glb = new Guid("463dcda2-81af-4e20-9405-d4810990715b");
        }

        public sealed class Prefabs
        {
            /// <summary> Asset Path (XRV/Prefabs/Manipulator.weprefab.weprf) </summary>
            public static readonly Guid Manipulator_weprefab = new Guid("d15e6e57-0f7d-4160-8935-b80d0cb14f12");
        }      
    }
}
