// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Xrv.Painter
{
    public sealed class PainterResourceIDs
    {
        public sealed class Materials
        {
            public sealed class Icons
            {
                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Icons/Painter.weprefab.weprf)
                /// </summary>
                public static readonly Guid Painter = new Guid("b70dcd75-78ac-4abf-a2af-011c5ebd458e");
            }
        }

        public sealed class Prefabs
        {
            /// <summary>
            /// Asset Path (XRV/Prefabs/Painter.weprefab.weprf)
            /// </summary>
            public static readonly Guid Painter = new Guid("e95ffbcf-a8e9-47f3-90a1-842e363d4c54");

            /// <summary>
            /// Asset Path (XRV/Prefabs/HelpPainer.weprefab.weprf)
            /// </summary>
            public static readonly Guid HelpPainer = new Guid("a0d8c73e-97d4-4f65-99d5-9d04c59da370");
        }
    }
}
