// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using Xrv.AudioNote.Models;

namespace Xrv.AudioNote.Messages
{
    public class AudioNoteDeleteMessage
    {
        public AudioNoteData Data { get; set; }
        public AudioNoteWindow Window { get; set; }
    }
}
