// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

namespace Xrv.AudioNote.Messages
{
    public class AudioAnchorSelected
    {
        public AudioNoteAnchor Anchor { get; set; }
    }
}
