// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using Evergine.Common.Attributes;

[assembly: EvergineAssembly(EvergineAssemblyUsage.Extension)]