// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Evergine.Xrv.Painter
{
    public sealed class PainterResourceIDs
    {
        public sealed class Materials
        {
            public sealed class Icons
            {
                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Icons/Painter.weprefab.weprf)
                /// </summary>
                public static readonly Guid Painter = new Guid("b70dcd75-78ac-4abf-a2af-011c5ebd458e");
            }

            public sealed class Colors
            {
                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Materials/Colors/BlueColor.wemt)
                /// </summary>
                public static readonly Guid BlueColor = new Guid("7434ac3b-5505-46dc-aaf2-e33bb013b517");

                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Materials/Colors/BlueDarkColor.wemt)
                /// </summary>
                public static readonly Guid BlueDarkColor = new Guid("7435ac3b-5505-46dc-a6f2-e33bb013b517");

                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Materials/Colors/GreenColor.wemt)
                /// </summary>
                public static readonly Guid GreenColor = new Guid("7436ac3b-5505-46dc-a6f2-e33bb013b517");

                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Materials/Colors/OrangeColor.wemt)
                /// </summary>
                public static readonly Guid OrangeColor = new Guid("7437ac3b-5505-46dc-a6f2-e33bb013b517");

                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Materials/Colors/PistachoColor.wemt)
                /// </summary>
                public static readonly Guid PistachoColor = new Guid("7438ac3b-5505-46dc-a6f2-e33bb013b517");

                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Materials/Colors/PurpleColor.wemt)
                /// </summary>
                public static readonly Guid PurpleColor = new Guid("7633ac3b-5505-46dc-a6f2-e33bb013b417");

                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Materials/Colors/RedColor.wemt)
                /// </summary>
                public static readonly Guid RedColor = new Guid("7439ac3b-5505-46dc-a6f2-e33bb013b517");

                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Materials/Colors/WhiteColor.wemt)
                /// </summary>
                public static readonly Guid WhiteColor = new Guid("7533ac3b-5505-46dc-a6f2-e33bb013b517");

                /// <summary>
                /// Asset Path (src/modules/Painter/addon/Content/XRV/Materials/Colors/YellowColor.wemt)
                /// </summary>
                public static readonly Guid YellowColor = new Guid("7633ac3b-5505-46dc-a6f2-e33bb013b517");
            }
        }

        public sealed class Prefabs
        {
            /// <summary>
            /// Asset Path (XRV/Prefabs/Painter.weprefab.weprf)
            /// </summary>
            public static readonly Guid Painter = new Guid("e95ffbcf-a8e9-47f3-90a1-842e363d4c54");

            /// <summary>
            /// Asset Path (XRV/Prefabs/HelpPainer.weprefab.weprf)
            /// </summary>
            public static readonly Guid HelpPainer = new Guid("a0d8c73e-97d4-4f65-99d5-9d04c59da370");

            /// <summary>
            /// Asset Path (XRV/Prefabs/LinePainter.weprefab.weprf)
            /// </summary>
            public static readonly Guid PointerPainter = new Guid("7dc1377a-f1cc-4f55-8807-137e07e0e81d");
        }
    }
}
