// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Evergine.Xrv.Core
{
    public static class CoreResourcesIDs
    {
        public static class Fonts
        {
            public static Guid Montserrat_Regular = new Guid("1c6e2929-d555-4c02-af49-50b4ecb01ce3");

            public static Guid Montserrat_SemiBold = new Guid("353e3432-ebdf-44f6-99cc-6b667efd14ba");
        }

        public static class Materials
        {
            public static class Icons
            {
                public static Guid Help = new Guid("c67d466a-5391-4f19-94ce-23f88c0a028d");

                public static Guid Settings = new Guid("5bd38b6b-d4d8-4451-9e35-1892c7de20fa");

                public static Guid ControlRequest = new Guid("15b023eb-a334-44b2-8cc1-d0d2ccae5b3c");

                public static readonly Guid Direction = new Guid("e9e9dce3-3f5b-40a5-bc70-8860024dfccb");

                public static readonly Guid Move = new Guid("68b9e5d2-e125-4e62-a804-963438a78df8");

                public static readonly Guid Lock = new Guid("0808d20e-31ce-4344-af5d-f7c9ca5d80b3");

                public static readonly Guid Unlock = new Guid("f59ad7f1-be68-4b4a-9fbe-0c9eb5d16459");

                public static readonly Guid info = new Guid("41710758-d61f-47ef-b81b-b273d15ae602");

                public static readonly Guid close = new Guid("55b023eb-a334-44b2-8cc1-d0d2ccae5b3c");

                public static readonly Guid follow = new Guid("fc03c81e-dc30-460b-be14-bf92963b12c3");

                public static readonly Guid pin = new Guid("6a3f5a9e-4c70-4a29-9e2b-a2ff3171b257");

                public static readonly Guid dots = new Guid("dd562e05-03e6-45f5-b79e-d32b8bd8f9e7");
            }

            public sealed class Networking
            {
                /// <summary> Asset Path (XRV/Materials/Networking/notification-icon.wemt) </summary>
                public static readonly Guid notification_icon = new Guid("8d98f911-dbff-43a9-9b53-585407156f1f");

                public sealed class Participants
                {
                    /// <summary> Asset Path (XRV/Materials/Networking/Participants/ControllerMarker.wemt) </summary>
                    public static readonly Guid ControllerMarker = new Guid("4d072e00-be00-420c-a5ed-e657b6f89836");
                }
            }


            public static class Services
            {
                public static class QR
                {
                    public static Guid ScannerBorder = new Guid("53e8b898-86d9-4e2a-b67d-ccb8568bfcb1");
                }
            }

            public static Guid PrimaryColor1 = new Guid("7433ac3b-5505-46dc-a6f2-e33bb013b519");

            public static Guid PrimaryColor2 = new Guid("88713f2f-e87d-4515-8a87-bbe4bc162bf5");

            public static Guid PrimaryColor3 = new Guid("b08e8a89-7a9a-4e5c-9a13-d2798932f3ef");

            public static Guid SecondaryColor1 = new Guid("7ebdc624-1d13-4b18-b38e-d5cce9bf64ce");

            public static Guid SecondaryColor2 = new Guid("6dc2a996-7fce-40d0-8ed2-f9dc2011b778");

            public static Guid SecondaryColor3 = new Guid("ce1f6bc9-39ac-4a0a-a913-07963f7342f5");

            public static Guid SecondaryColor4 = new Guid("963fcfba-66ad-4ca7-ab91-f3c557357b5f");

            public static Guid logoMaterial = new Guid("db59d1e4-43a8-4e6b-94c8-bf5bf44a7d7b");

            public static Guid BorderlessFrontPlate = new Guid("117070d5-cccf-4b60-93c8-eddafd9b51d5");

            public static Guid FrontPlateMaterial = new Guid("1a7070d5-cccf-4b60-93c8-eddafd9b51d5");

            /// <summary> Asset Path (XRV/Materials/HandTutorial.wemt) </summary>
            public static readonly Guid HandTutorial = new Guid("66f1bb1f-95e9-49a6-9a59-88371ccc8a16");
        }

        public sealed class Models
        {
            /// <summary> Asset Path (XRV/Models/Hand_Panel_anim.glb.wemd) </summary>
            public static readonly Guid Hand_Panel_anim_glb = new Guid("769ab5a4-32b4-4b30-945a-3f121608ed88");
        }

        public static class Prefabs
        {
            public static Guid About_weprefab = new Guid("adf890cb-87ff-4ddf-be94-98472df4ebb0");

            public static Guid BaseDialogContents = new Guid("a3566fc1-12f4-4545-93a7-8f7e1da22a36");

            public static Guid GeneralHelp_weprefab = new Guid("d16caec5-e260-47ce-a812-15f98c31d0ad");

            public static Guid GeneralSettings_weprefab = new Guid("372c3942-5cf9-4ef0-a88e-d162a4b4abe1");

            public static Guid HandMenu = new Guid("890eb664-4c07-4b33-afca-7e428b2fbc11");

            public static Guid TabControl = new Guid("4cd4a3d9-33e4-4b2a-8dbf-5b25aa014a0b");

            public static Guid TextButton = new Guid("69925256-16a0-4938-81fb-2810f6afa4eb");

            public static Guid Window = new Guid("76a3430f-9ddd-4536-abef-d51e7d67e444");

            public static readonly Guid iconTextButton_weprefab = new Guid("6c2abc65-102e-4516-b8c2-f2886322f5a3");

            public static class Networking
            {
                public static readonly Guid ManualMarker_weprefab = new Guid("6bb8a823-7660-45cf-b0bb-9555615ab6a9");

                public static Guid SessionSettings_weprefab = new Guid("6c05a9e8-7b69-4c52-9bbd-223fed12ee83");

                public sealed class Participants
                {
                    /// <summary> Asset Path (XRV/Prefabs/Networking/Participants/DefaultHead.weprefab.weprf) </summary>
                    public static readonly Guid DefaultHead_weprefab = new Guid("34b5a455-2449-4ccb-afad-91bbff013a01");

                    /// <summary> Asset Path (XRV/Prefabs/Networking/Participants/HoloLensHead.weprefab.weprf) </summary>
                    public static readonly Guid HoloLensHead_weprefab = new Guid("c99aa11c-e668-419f-89c6-fcd910259b4d");

                    public static readonly Guid leftPalm_weprefab = new Guid("1a475651-6e98-4a28-8462-c56902a20f87");

                    public static readonly Guid rightPalm_weprefab = new Guid("f2cc2ae2-ed1b-4656-aff2-77367d3b525f");
                }
            }

            public static class Services
            {
                public static class QR
                {
                    public static Guid QrMarker_weprefab = new Guid("56ab9099-2cc9-4606-b59c-b631983a7926");

                    public static Guid QrScanner_weprefab = new Guid("1a3917ef-322f-4563-9be5-68690e539f71");
                }
            }

            public sealed class Windows
            {

                /// <summary> Asset Path (XRV/Prefabs/Windows/BaseDialogContents.weprefab.weprf) </summary>
                public static readonly Guid BaseDialogContents_weprefab = new Guid("a3566fc1-12f4-4545-93a7-8f7e1da22a36");

                /// <summary> Asset Path (XRV/Prefabs/Windows/NotificationHub.weprefab.weprf) </summary>
                public static readonly Guid NotificationHub_weprefab = new Guid("b93120ee-a1b5-4305-a344-c9efc5a7eda8");

                /// <summary> Asset Path (XRV/Prefabs/Windows/window.weprefab.weprf) </summary>
                public static readonly Guid window_weprefab = new Guid("76a3430f-9ddd-4536-abef-d51e7d67e444");
            }
        }

        public static class Textures
        {
            public static Guid IridescentSpectrum = new Guid("ba547d15-0927-4bfe-b7da-6625fdd7d9a5");
        }
    }
}
