// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using Evergine.Framework;
using Evergine.Framework.Graphics;
using Evergine.Framework.Prefabs;
using Evergine.Framework.Services;
using Evergine.Mathematics;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xrv.AudioNote.Messages;
using Xrv.AudioNote.Models;
using Xrv.AudioNote.Services;
using Xrv.Core;
using Xrv.Core.Menu;
using Xrv.Core.Modules;
using Xrv.Core.UI.Dialogs;
using Xrv.Core.UI.Tabs;
using Xrv.Core.UI.Windows;

namespace Xrv.AudioNote
{
    public class AudioNoteModule : Module
    {
        public override string Name => "AudioNote";

        public override HandMenuButtonDescription HandMenuButton => this.handMenuDesc;

        public override TabItem Help => this.help;

        public override TabItem Settings => this.settings;

        protected AssetsService assetsService;
        private XrvService xrv;
        private HandMenuButtonDescription handMenuDesc;
        private TabItem settings;
        private TabItem help;

        private Entity audioNoteHelp;
        private Entity audioNoteSettings;
        private Window window;
        private Scene scene;
        private AudioNoteAnchor lastAnchorSelected;

        private Dictionary<string, Entity> anchorsDic = new Dictionary<string, Entity>();
        private AudioNoteDeleteMessage audionoteToRemove;

        public AudioNoteModule()
        {
            this.handMenuDesc = new HandMenuButtonDescription()
            {
                IconOn = AudioNoteResourceIDs.Materials.Icons.AudioNote,
                IsToggle = false,
                TextOn = "Audio Note",
            };

            //this.settings = new TabItem()
            //{
            //    Name = "Audio Note",
            //    Contents = SettingContent,
            //};
            this.settings = null;

            this.help = new TabItem()
            {
                Name = "Audio Note",
                Contents = HelpContent,
            };

            Application.Current.Container.RegisterInstance(new PlaybackService());
            Application.Current.Container.RegisterInstance(new RecordingService());
        }

        public override void Initialize(Scene scene)
        {
            this.assetsService = Application.Current.Container.Resolve<AssetsService>();
            this.xrv = Application.Current.Container.Resolve<XrvService>();
            this.scene = scene;

            // Settings
            //var audioSettingPrefab = this.assetsService.Load<Prefab>(AudioNoteResourceIDs.Prefabs.Settings);
            //this.audioNoteSettings = audioSettingPrefab.Instantiate();

            this.window = this.ShowAudionoteWindow(AudioNoteResourceIDs.Prefabs.Window);

            this.xrv.PubSub.Subscribe<AudioAnchorSelected>(this.CreateAudioNoteWindow);
            this.xrv.PubSub.Subscribe<AudioNoteDeleteMessage>(this.ConfirmDelete);
        }

        public override void Run(bool turnOn)
        {
            var anchor = this.assetsService.Load<Prefab>(AudioNoteResourceIDs.Prefabs.Anchor).Instantiate();

            this.SetFrontPosition(this.scene, anchor);
            this.AddAudioAnchor(anchor);

            this.xrv.PubSub.Publish(new AudioAnchorSelected()
            {
                Anchor = anchor.FindComponent<AudioNoteAnchor>(),
            });
        }

        private void AddAudioAnchor(Entity anchor)
        {
            var c = anchor.FindComponent<AudioNoteAnchor>();
            if (c != null)
            {
                this.scene.Managers.EntityManager.Add(anchor);
                anchorsDic.Add(c.AudioNote.Guid, anchor);
            }
        }

        public Vector3 GetFrontPosition(Scene scene)
        {
            var cameraTransform = scene.Managers.RenderManager.ActiveCamera3D.Transform;
            var cameraWorldTransform = cameraTransform.WorldTransform;
            return cameraTransform.Position + cameraWorldTransform.Forward * this.xrv.WindowSystem.Distances.Medium;
        }

        public void SetFrontPosition(Scene scene, Entity entity)
        {
            var anchorTransform = entity.FindComponent<Transform3D>();
            anchorTransform.Position = this.GetFrontPosition(scene);
        }

        private Entity SettingContent()
        {
            return this.audioNoteSettings;
        }

        private Entity HelpContent()
        {
            if (this.audioNoteHelp == null)
            {
                var audioHelpPrefab = this.assetsService.Load<Prefab>(AudioNoteResourceIDs.Prefabs.Help);
                this.audioNoteHelp = audioHelpPrefab.Instantiate();
            }

            return this.audioNoteHelp;
        }

        private void CreateAudioNoteWindow(AudioAnchorSelected msg)
        {
            this.window.Open();

            if (lastAnchorSelected != null)
            {
                this.lastAnchorSelected.UpdateVisualState(AudioNoteAnchorVisual.Idle);
                this.lastAnchorSelected.IsSelected = false;
            }

            msg.Anchor.UpdateVisualState(AudioNoteAnchorVisual.Selected);
            msg.Anchor.IsSelected = true;
            this.lastAnchorSelected = msg.Anchor;

            _ = this.SetWindowInitialState(msg.Anchor.AudioNote);
        }

        private async Task<bool> SetWindowInitialState(AudioNoteData data)
        {
            var ok = true;
            var note = this.window.Owner.FindComponentInChildren<AudioNoteWindow>();

            if (note.WindowState == AudioNoteWindowState.Recording)
            {
                ok = await note.StopRecordingAsync();
            }

            note.Data = data;
            this.window.Open();
            if (string.IsNullOrEmpty(data.Path))
            {
                ok &= await note.StartRecordingAsync();
            }
            else
            {
                ok &= await note.StartPlayingAsync();
            }

            return ok;
        }

        private void ConfirmDelete(AudioNoteDeleteMessage msg)
        {
            var confirmDelete = this.xrv.WindowSystem.ShowConfirmDialog("Delete this note?", "This action can’t be undone.", "No", "Yes");

            confirmDelete.Open();
            this.audionoteToRemove = msg;
            confirmDelete.Closed += Alert_Closed;
        }

        private void Alert_Closed(object sender, System.EventArgs e)
        {
            if (sender is Dialog dialog)
            {
                dialog.Closed -= this.Alert_Closed;
                var audioNote = this.audionoteToRemove;
                this.audionoteToRemove = null;

                var isAcceted = dialog.Result == ConfirmDialog.AcceptKey;
                if (!isAcceted) return;

                var guid = audioNote?.Data.Guid;
                if (string.IsNullOrEmpty(guid)) return;

                _ = audioNote.Window.StopRecordingAsync(false);
                this.RemoveAnchor(guid);
                this.window.Close();
            }
        }

        public void RemoveAnchor(string guid)
        {
            this.lastAnchorSelected = null;

            // TODO when anchor is serialized, remove from there also
            if (this.anchorsDic.TryGetValue(guid, out var anchor))
            {
                this.scene.Managers.EntityManager.Remove(anchor);
            }
        }

        private Window ShowAudionoteWindow(Guid prefabId)
        {
            var audioNoteSize = new Vector2(0.18f, 0.04f);
            var window = this.xrv.WindowSystem.CreateWindow((config) =>
            {
                config.Title = "Audio Note";
                config.Size = audioNoteSize;
                config.FrontPlateSize = audioNoteSize;
                config.FrontPlateOffsets = Vector2.Zero;
                config.DisplayLogo = false;
                config.Content = this.assetsService.Load<Prefab>(prefabId).Instantiate();
            });

            return window;
        }
    }
}
