//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evergine.Xrv.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evergine.Xrv.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Global_Accept {
            get {
                return ResourceManager.GetString("Global.Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Global_Cancel {
            get {
                return ResourceManager.GetString("Global.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Global_No {
            get {
                return ResourceManager.GetString("Global.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Global_Ok {
            get {
                return ResourceManager.GetString("Global.Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Global_Yes {
            get {
                return ResourceManager.GetString("Global.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Help_Tab_About {
            get {
                return ResourceManager.GetString("Help.Tab.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Help_Tab_General {
            get {
                return ResourceManager.GetString("Help.Tab.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help_Title {
            get {
                return ResourceManager.GetString("Help.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Menu_Close {
            get {
                return ResourceManager.GetString("Menu.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach.
        /// </summary>
        internal static string Menu_Detach {
            get {
                return ResourceManager.GetString("Menu.Detach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Menu_Follow {
            get {
                return ResourceManager.GetString("Menu.Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string Menu_Pin {
            get {
                return ResourceManager.GetString("Menu.Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request control.
        /// </summary>
        internal static string Networking_Menu_RequestControl {
            get {
                return ResourceManager.GetString("Networking.Menu.RequestControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning....
        /// </summary>
        internal static string Services_QR_HubTitle {
            get {
                return ResourceManager.GetString("Services.QR.HubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session host has taken session control.
        /// </summary>
        internal static string Sessions_Control_LostDialogMessage {
            get {
                return ResourceManager.GetString("Sessions.Control.LostDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control lost.
        /// </summary>
        internal static string Sessions_Control_LostDialogTitle {
            get {
                return ResourceManager.GetString("Sessions.Control.LostDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone has requested to take control.\nDo you agree?.
        /// </summary>
        internal static string Sessions_Control_RequestDialogMessage {
            get {
                return ResourceManager.GetString("Sessions.Control.RequestDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control request.
        /// </summary>
        internal static string Sessions_Control_RequestDialogTitle {
            get {
                return ResourceManager.GetString("Sessions.Control.RequestDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice recognition status.
        /// </summary>
        internal static string Settings_General_Voice_Title {
            get {
                return ResourceManager.GetString("Settings.General.Voice.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Off.
        /// </summary>
        internal static string Settings_General_VoiceOff {
            get {
                return ResourceManager.GetString("Settings.General.VoiceOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice On.
        /// </summary>
        internal static string Settings_General_VoiceOn {
            get {
                return ResourceManager.GetString("Settings.General.VoiceOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Menu {
            get {
                return ResourceManager.GetString("Settings.Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Settings_Sessions_Create_ButtonText {
            get {
                return ResourceManager.GetString("Settings.Sessions.Create.ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not start session.
        /// </summary>
        internal static string Settings_Sessions_Create_Error {
            get {
                return ResourceManager.GetString("Settings.Sessions.Create.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Session.
        /// </summary>
        internal static string Settings_Sessions_Create_Label {
            get {
                return ResourceManager.GetString("Settings.Sessions.Create.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session #{0}.
        /// </summary>
        internal static string Settings_Sessions_Create_SessionName {
            get {
                return ResourceManager.GetString("Settings.Sessions.Create.SessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Session.
        /// </summary>
        internal static string Settings_Sessions_End_ButtonText {
            get {
                return ResourceManager.GetString("Settings.Sessions.End.ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you end the session, it will finish for anyone connected.
        /// </summary>
        internal static string Settings_Sessions_End_EndSessionConfirmationMessage {
            get {
                return ResourceManager.GetString("Settings.Sessions.End.EndSessionConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End session?.
        /// </summary>
        internal static string Settings_Sessions_End_EndSessionConfirmationTitle {
            get {
                return ResourceManager.GetString("Settings.Sessions.End.EndSessionConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error leaving session.
        /// </summary>
        internal static string Settings_Sessions_End_Error {
            get {
                return ResourceManager.GetString("Settings.Sessions.End.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can join again to the session, if it is still available.
        /// </summary>
        internal static string Settings_Sessions_End_LeaveSessionConfirmationMessage {
            get {
                return ResourceManager.GetString("Settings.Sessions.End.LeaveSessionConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave session?.
        /// </summary>
        internal static string Settings_Sessions_End_LeaveSessionConfirmationTitle {
            get {
                return ResourceManager.GetString("Settings.Sessions.End.LeaveSessionConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Settings_Sessions_Join_ButtonText {
            get {
                return ResourceManager.GetString("Settings.Sessions.Join.ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not join session.
        /// </summary>
        internal static string Settings_Sessions_Join_Error {
            get {
                return ResourceManager.GetString("Settings.Sessions.Join.Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Session.
        /// </summary>
        internal static string Settings_Sessions_Join_Label {
            get {
                return ResourceManager.GetString("Settings.Sessions.Join.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No session found.
        /// </summary>
        internal static string Settings_Sessions_Join_NoSessionsFound {
            get {
                return ResourceManager.GetString("Settings.Sessions.Join.NoSessionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a session.
        /// </summary>
        internal static string Settings_Sessions_Join_SelectorPlaceholder {
            get {
                return ResourceManager.GetString("Settings.Sessions.Join.SelectorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have joined #{0}.
        /// </summary>
        internal static string Settings_Sessions_Joined_StatusTextAsClient {
            get {
                return ResourceManager.GetString("Settings.Sessions.Joined.StatusTextAsClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have created and joined #{0}.
        /// </summary>
        internal static string Settings_Sessions_Joined_StatusTextAsServer {
            get {
                return ResourceManager.GetString("Settings.Sessions.Joined.StatusTextAsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating session....
        /// </summary>
        internal static string Settings_Sessions_Joining_CreationInProgress {
            get {
                return ResourceManager.GetString("Settings.Sessions.Joining.CreationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining session....
        /// </summary>
        internal static string Settings_Sessions_Joining_JoinInProgress {
            get {
                return ResourceManager.GetString("Settings.Sessions.Joining.JoinInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Settings_Tab_General {
            get {
                return ResourceManager.GetString("Settings.Tab.General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        internal static string Settings_Tab_Sessions {
            get {
                return ResourceManager.GetString("Settings.Tab.Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Window_Button_Close {
            get {
                return ResourceManager.GetString("Window.Button.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        internal static string Window_Button_Follow {
            get {
                return ResourceManager.GetString("Window.Button.Follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        internal static string Window_Button_Pin {
            get {
                return ResourceManager.GetString("Window.Button.Pin", resourceCulture);
            }
        }
    }
}
