// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;
using System.Collections.Generic;
using System.Text;

namespace Xrv.AudioNote.Models
{
    public class AudioNoteData
    {
        public string Guid { get; set; }
        public string Path { get; set; }
    }
}
