//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrv.LoadModel.Effects
{
    using Evergine.Common.Graphics;
    using Evergine.Framework.Graphics;
    using Evergine.Framework.Graphics.Effects;
    using Evergine.Mathematics;
    
    
    [Evergine.Framework.Graphics.MaterialDecoratorAttribute("d0d24ac6-f92d-455a-96e3-7957d219772b")]
    public partial class SolidEffect : Evergine.Framework.Graphics.MaterialDecorator
    {
        
        public SolidEffect(Evergine.Framework.Graphics.Effects.Effect effect) : 
                base(new Material(effect))
        {
        }
        
        public SolidEffect(Evergine.Framework.Graphics.Material material) : 
                base(material)
        {
        }
        
        public Evergine.Mathematics.Matrix4x4 PerDrawCall_World
        {
            get
            {
                return this.material.CBuffers[0].GetBufferData<Evergine.Mathematics.Matrix4x4>(0);
            }
            set
            {
				this.material.CBuffers[0].SetBufferData(value, 0);
            }
        }
        
        public Evergine.Mathematics.Vector3 PerCamera_SunDirection
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<Evergine.Mathematics.Vector3>(0);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 0);
            }
        }
        
        public float PerCamera_SunIntensity
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<System.Single>(12);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 12);
            }
        }
        
        public int PerCamera_EyeCount
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<System.Int32>(16);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 16);
            }
        }
        
        public Evergine.Mathematics.Matrix4x4 PerCamera_ViewProj
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<Evergine.Mathematics.Matrix4x4>(32);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 32);
            }
        }
        
        public Evergine.Mathematics.Matrix4x4 PerCamera_MultiviewViewProj
        {
            get
            {
                return this.material.CBuffers[1].GetBufferData<Evergine.Mathematics.Matrix4x4>(96);
            }
            set
            {
				this.material.CBuffers[1].SetBufferData(value, 96);
            }
        }
        
        public Evergine.Mathematics.Vector3 Parameters_Color
        {
            get
            {
                return this.material.CBuffers[2].GetBufferData<Evergine.Mathematics.Vector3>(0);
            }
            set
            {
				this.material.CBuffers[2].SetBufferData(value, 0);
            }
        }
        
        public float Parameters_Alpha
        {
            get
            {
                return this.material.CBuffers[2].GetBufferData<System.Single>(12);
            }
            set
            {
				this.material.CBuffers[2].SetBufferData(value, 12);
            }
        }
        
        public float Parameters_Ambient
        {
            get
            {
                return this.material.CBuffers[2].GetBufferData<System.Single>(16);
            }
            set
            {
				this.material.CBuffers[2].SetBufferData(value, 16);
            }
        }
        
        public float Parameters_AlphaCutOff
        {
            get
            {
                return this.material.CBuffers[2].GetBufferData<System.Single>(20);
            }
            set
            {
				this.material.CBuffers[2].SetBufferData(value, 20);
            }
        }
        
        public Evergine.Common.Graphics.Texture BaseColorTexture
        {
            get
            {
                return this.material.TextureSlots[0].Texture;
            }
            set
            {
				this.material.SetTexture(value, 0);
            }
        }
        
        public Evergine.Common.Graphics.SamplerState BaseColorSampler
        {
            get
            {
                return this.material.SamplerSlots[0].Sampler;
            }
            set
            {
				this.material.SetSampler(value, 0);
            }
        }
    }
}
