// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Xrv.Core
{
    public static class CoreResourcesIDs
    {
        public static class Materials
        {
            public static class Icons
            {
                public static Guid Help = new Guid("c67d466a-5391-4f19-94ce-23f88c0a028d");

                public static Guid Settings = new Guid("5bd38b6b-d4d8-4451-9e35-1892c7de20fa");
            }

            public static Guid logoMaterial = new Guid("db59d1e4-43a8-4e6b-94c8-bf5bf44a7d7b");
        }

        public static class Mrtk
        {
            public static class Prefabs
            {
                public static Guid PressableButtonPlated = new Guid("dabe9073-b1d1-42c5-99b9-ebc0cb4a7430");
            }
        }

        public static class Prefabs
        {
            public static Guid BaseDialogContents = new Guid("f544117b-51ca-46af-894e-49a48094651f");

            public static Guid HandMenu = new Guid("bf71482f-e2ca-41ea-bc66-a8422663e178");

            public static Guid TabControl = new Guid("4cd4a3d9-33e4-4b2a-8dbf-5b25aa014a0b");

            public static Guid TextButton = new Guid("69925256-16a0-4938-81fb-2810f6afa4eb");

            public static Guid Window = new Guid("6083dd5c-6f8b-4b07-b501-933c59401982");

            public static Guid GeneralHelp_weprefab = new Guid("4ab4d356-6777-4d70-b55a-c374647d8e1d");

            public static Guid About_weprefab = new Guid("adf890cb-87ff-4ddf-be94-98472df4ebb0");
        }
    }
}
