// Copyright © Plain Concepts S.L.U. All rights reserved. Use is subject to license terms.
// <auto-generated />

using System;

namespace Xrv.Core
{
    public static class CoreResourcesIDs
    {
        public static class Materials
        {
            public static class Icons
            {
                public static Guid Help = new Guid("c67d466a-5391-4f19-94ce-23f88c0a028d");

                public static Guid Settings = new Guid("5bd38b6b-d4d8-4451-9e35-1892c7de20fa");
            }

            public static Guid PrimaryColor1 = new Guid("7433ac3b-5505-46dc-a6f2-e33bb013b519");

            public static Guid PrimaryColor2 = new Guid("88713f2f-e87d-4515-8a87-bbe4bc162bf5");

            public static Guid PrimaryColor3 = new Guid("b08e8a89-7a9a-4e5c-9a13-d2798932f3ef");

            public static Guid SecondaryColor1 = new Guid("7ebdc624-1d13-4b18-b38e-d5cce9bf64ce");

            public static Guid SecondaryColor2 = new Guid("6dc2a996-7fce-40d0-8ed2-f9dc2011b778");

            public static Guid SecondaryColor3 = new Guid("ce1f6bc9-39ac-4a0a-a913-07963f7342f5");

            public static Guid SecondaryColor4 = new Guid("963fcfba-66ad-4ca7-ab91-f3c557357b5f");

            public static Guid logoMaterial = new Guid("db59d1e4-43a8-4e6b-94c8-bf5bf44a7d7b");

            public static Guid BorderlessFrontPlate = new Guid("117070d5-cccf-4b60-93c8-eddafd9b51d5");

            public static Guid FrontPlateMaterial = new Guid("1a7070d5-cccf-4b60-93c8-eddafd9b51d5");
        }

        public static class Prefabs
        {
            public static Guid About_weprefab = new Guid("adf890cb-87ff-4ddf-be94-98472df4ebb0");

            public static Guid BaseDialogContents = new Guid("f544117b-51ca-46af-894e-49a48094651f");

            public static Guid GeneralHelp_weprefab = new Guid("d16caec5-e260-47ce-a812-15f98c31d0ad");

            public static Guid GeneralSettings_weprefab = new Guid("372c3942-5cf9-4ef0-a88e-d162a4b4abe1");

            public static Guid HandMenu = new Guid("890eb664-4c07-4b33-afca-7e428b2fbc11");

            public static Guid TabControl = new Guid("4cd4a3d9-33e4-4b2a-8dbf-5b25aa014a0b");

            public static Guid TextButton = new Guid("69925256-16a0-4938-81fb-2810f6afa4eb");

            public static Guid Window = new Guid("76a3430f-9ddd-4536-abef-d51e7d67e444");
        }

        public static class Textures
        {
            public static Guid IridescentSpectrum = new Guid("ba547d15-0927-4bfe-b7da-6625fdd7d9a5");
        }
    }
}
