name: CD Nightly
on:
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      isPackagingBuild: true
      versionSuffix: rolling #nightly
  #publish:
  #  needs: build
  #  uses: ./.github/workflows/publish.yaml
  #  with:
  #    version: ${{ needs.build.outputs.version }}
  #    storageAccountName: everginestudio
  #    blobsContainerName: pkg-nightly
  #    nugetSourceUrl: "https://pkgs.dev.azure.com/plainconcepts/Evergine.Nightly/_packaging/Evergine.NightlyBuilds/nuget/v3/index.json"
  #  secrets:
  #    archiveSasToken: ${{ secrets.PUBLISH_FILE_SHARE_ARCHIVE_SAS_TOKEN }}
  #    blobContainerSasToken: ${{ secrets.PUBLISH_NIGHTLY_BLOB_CONTAINER_SAS_TOKEN }}
  #    nugetToken: ${{ secrets.PUBLISH_NIGHTLY_NUGET_TOKEN }}