name: CI
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  workflow_dispatch:
jobs:
  build-xrv:
    uses: EvergineTeam/XRV/.github/workflows/build.yaml@feature/prepare-packaging
    with:
      isPackagingBuild: false
