name: CI
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
  workflow_dispatch:
jobs:
  build-xrv:
    uses: ./.github/workflows/build.yaml
    with:
      isPackagingBuild: false
