name: CI
on:
  push:
    branches:
    - develop
    - main
  pull_request:
    branches:
    - develop
    - main
  workflow_dispatch:
jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      isPackagingBuild: false
